// <auto-generated />
namespace MyTimeTracking.Data.EF.Migration.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateUserIdToGuidID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateUserIdToGuidID));
        
        string IMigrationMetadata.Id
        {
            get { return "201703261254351_updateUserIdToGuidID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
